import type { Batch, Trip, TripIndexEntry } from "@/types/content";

export const tripIndex: TripIndexEntry[] = [
  { slug: "manali-snow-camp", name: "Manali Snow Camp", region: "across-india" },
  { slug: "astro-adventure-manali", name: "Astro Adventure Trekking Camp", region: "across-india" },
  { slug: "ladakh-trek", name: "Ladakh Trek", region: "across-india" },
  { slug: "grand-uttaranchal-trek", name: "Grand Uttaranchal Trek", region: "across-india" },
  { slug: "nainital-almora-binsar", name: "Nainital, Almora & Binsar", region: "across-india" },
  { slug: "leh-ladakh-circuit", name: "Leh Ladakh Circuit", region: "across-india" },
  { slug: "shimla-manali-amritsar", name: "Shimla, Manali & Amritsar", region: "across-india" },
  { slug: "kullu-shimla-manali", name: "Kullu, Shimla & Manali", region: "across-india" },
  { slug: "kullu-manali-dalhousie", name: "Kullu, Manali & Dalhousie", region: "across-india" },
  { slug: "nainital-mussoorie-corbett", name: "Nainital, Mussoorie & Corbett", region: "across-india" },
  { slug: "mount-abu", name: "Mount Abu", region: "across-india" },
  { slug: "rajasthan-heritage", name: "Rajasthan Heritage Tour", region: "across-india" },
  { slug: "lonavala", name: "Lonavala", region: "across-india" },
  { slug: "panchgani-mahabaleshwar", name: "Panchgani & Mahabaleshwar", region: "across-india" },
  { slug: "pachmarhi", name: "Pachmarhi", region: "across-india" },
  { slug: "jabalpur-kanha", name: "Jabalpur, Bhedaghat & Kanha", region: "across-india" },
  { slug: "goa", name: "Goa", region: "across-india" },
  { slug: "kerala", name: "Kerala", region: "across-india" },
  { slug: "karnataka", name: "Karnataka", region: "across-india" },
  { slug: "odisha", name: "Odisha", region: "across-india" },
  { slug: "sikkim-trek", name: "Sikkim Trek", region: "north-east" },
  { slug: "everest-base-camp", name: "Everest Base Camp Trek", region: "outside-india" },
  { slug: "bet-dwarka-marine-camp", name: "Marine Camp, Bet Dwarka", region: "gujarat" },
  { slug: "narara", name: "Narara Island Coral Walk", region: "gujarat" },
  { slug: "sasan-gir", name: "Sasan Gir Wildlife Camp", region: "gujarat" },
  { slug: "osam-hill", name: "Osam Hill, Patanvav", region: "gujarat" },
  { slug: "hingolgadh-nature-camp", name: "Hingolgadh Nature Camp", region: "gujarat" },
  { slug: "kutch", name: "Kutch Nature Camp", region: "gujarat" },
  { slug: "saputara", name: "Saputara, Dang Forest", region: "gujarat" },
  { slug: "diu", name: "Diu Coastal Camp", region: "gujarat" },
  { slug: "dwarka-somnath-diu", name: "Dwarka, Somnath & Diu", region: "gujarat" },
  { slug: "dwarka-somnath", name: "Dwarka & Somnath", region: "gujarat" },
  { slug: "rann-of-kutch-dholavira", name: "Rann of Kutch & Dholavira", region: "gujarat" },
  { slug: "white-rann-of-kutch", name: "White Rann of Kutch", region: "gujarat" },
  { slug: "gir-diu", name: "Gir Wildlife & Diu Beach", region: "gujarat" },
];

export const trips: Trip[] = [
  {
    slug: "manali-snow-camp",
    name: "Manali Snow Camp",
    region: "across-india",
    type: "Trek",
    location: "Himachal Pradesh",
    summary: "Skiing, snowboarding and snow walks near our Manali campus, January to mid-March.",
    duration: "6D/5N",
    altitudeM: 3000,
    difficulty: "Easy",
    priceFrom: null,
    image: { src: "/img/cna/manali/01.webp", alt: "Campers on a snow slope at the Manali Snow Camp" },
  },
  {
    slug: "astro-adventure-manali",
    name: "Astro Adventure Trekking Camp",
    region: "across-india",
    type: "Trek",
    location: "Himachal Pradesh",
    summary:
      "Trekking, rafting, climbing and night-sky sessions in Manali. The Adventure Olympiad scholarship camp.",
    duration: "10D/9N",
    altitudeM: 4000,
    difficulty: "Moderate",
    priceFrom: 18000,
    image: { src: "/img/cna/manali/11.webp", alt: "A CNA group on a mountain trail near Manali" },
  },
  {
    slug: "sikkim-trek",
    name: "Sikkim Trek",
    region: "north-east",
    type: "Trek",
    location: "Sikkim",
    summary: "Gangtok, the glacial Tsomgo lake at 3,750 m and rafting on the Teesta.",
    duration: "9D/8N",
    altitudeM: 3750,
    difficulty: "Easy",
    priceFrom: null,
    image: { src: "/img/cna/sikkim/03.webp", alt: "Trekkers in the mountains of Sikkim" },
  },
  {
    slug: "everest-base-camp",
    name: "Everest Base Camp Trek",
    region: "outside-india",
    type: "Trek",
    location: "Nepal",
    summary:
      "The classic Khumbu trek to Everest Base Camp (5,364 m) and the view from Kala Patthar (5,545 m).",
    duration: "18D/17N",
    altitudeM: 5364,
    difficulty: "Challenging",
    priceFrom: null,
    image: { src: "/img/cna/everest_base_camp/05.webp", alt: "Trekkers on the Everest Base Camp trail" },
  },
  {
    slug: "bet-dwarka-marine-camp",
    name: "Marine Camp, Bet Dwarka",
    region: "gujarat",
    type: "Camp",
    location: "Devbhumi Dwarka",
    summary:
      "Where CNA began in 1997: low-tide walks among corals, starfish and sea life at the mouth of the Gulf of Kutch.",
    duration: "4D/3N",
    difficulty: "Easy",
    priceFrom: null,
    image: { src: "/img/cna/marinecamp/02.webp", alt: "Campers exploring the shore at Bet Dwarka at low tide" },
  },
  {
    slug: "sasan-gir",
    name: "Sasan Gir Wildlife Camp",
    region: "gujarat",
    type: "Camp",
    location: "Junagadh",
    summary: "Three days in the last wild home of the Asiatic lion: safari, forest walks and campfire nights.",
    duration: "3D/2N",
    difficulty: "Easy",
    priceFrom: null,
    image: { src: "/img/cna/sasangir/02.webp", alt: "A CNA group in the Gir forest" },
  },
  {
    slug: "osam-hill",
    name: "Osam Hill, Patanvav",
    region: "gujarat",
    type: "Camp",
    location: "Rajkot",
    summary: "A one-day trek on a green hill near Rajkot, with old temples and the Bhim Kund pool.",
    duration: "Day trip",
    difficulty: "Easy",
    priceFrom: null,
    image: { src: "/img/cna/osamhill/04.webp", alt: "Campers on Osam Hill near Rajkot" },
  },
  {
    slug: "grand-uttaranchal-trek",
    name: "Grand Uttaranchal Trek",
    region: "across-india",
    type: "Trek",
    location: "Uttarakhand",
    summary: "Rafting on the Ganga, the Neelkanth trek, Mussoorie and a jungle safari at Rajaji.",
    duration: "7D/6N",
    priceFrom: null,
    image: { src: "/img/cna/uttaranchal/02.webp", alt: "A CNA group trekking in Uttarakhand" },
  },
];

export const popularTripSlugs = [
  "manali-snow-camp",
  "astro-adventure-manali",
  "sikkim-trek",
  "everest-base-camp",
  "bet-dwarka-marine-camp",
  "sasan-gir",
];

export const batches: Batch[] = [
  { id: "osam-2026-10-17", tripSlug: "osam-hill", startDate: "2026-10-17", note: "Weekend", seatsLeft: 12 },
  { id: "astro-2026-10-21", tripSlug: "astro-adventure-manali", startDate: "2026-10-21", note: "Diwali break", seatsLeft: 6 },
  { id: "sikkim-2026-11-05", tripSlug: "sikkim-trek", startDate: "2026-11-05", seatsLeft: 9 },
  { id: "gut-2026-11-14", tripSlug: "grand-uttaranchal-trek", startDate: "2026-11-14", note: "Girls-only batch", seatsLeft: 8 },
  { id: "marine-2026-11-20", tripSlug: "bet-dwarka-marine-camp", startDate: "2026-11-20", note: "Low-tide window", seatsLeft: 20 },
];
