import type { Batch, PhotoKey, Trip } from "../../types/content";

/** Trip as written in the approved design: photos are design keys, files under /public/img. */
export type SeedTrip = Omit<Trip, "img" | "gallery" | "included" | "notIncluded" | "faqs" | "isSample" | "seo"> & {
  img: PhotoKey;
  gallery: PhotoKey[];
};

// Initial trip content from the approved design, imported into the CMS by the seed script.
export const trips: SeedTrip[] = [
  {
    slug: "manali-snow-camp",
    name: "Manali Snow Camp",
    region: "across-india",
    state: "Himachal Pradesh",
    type: "Trek",
    days: 6,
    nights: 5,
    altitude: "3,000 m",
    difficulty: "Easy",
    price: null,
    img: "cna/manali/01",
    gallery: ["cna/manali/01", "cna/manali/02", "cna/manali/06", "cna/manali/04", "cna/manali/08", "cna/manali/07", "cna/manali/05", "cna/manali/03", "cna/manali/09", "cna/manali/10", "cna/manali/11"],
    months: ["Jan", "Feb", "Mar"],
    start: "Ahmedabad",
    activities: ["Skiing", "Snowboarding", "Snow trek", "Nature education"],
    campus: "manali",
    featured: true,
    summary: "Skiing, snowboarding and snow walks near our Manali campus, January to mid-March.",
    overview: "Manali sits at the head of the Kullu valley, with snow peaks almost within arm’s reach. In January, February and the first half of March the slopes around Solang are covered in snow, and CNA runs a 5-night / 6-day skiing and snowboarding programme from our own campus in Vashisht. Trained instructors teach the basics; the rest of the day is snow walks, nature education and warm evenings at camp.",
    bring: ["Thermal inner wear (2 sets)", "Fleece + down jacket", "Woollen cap, gloves & socks", "Waterproof shoes", "4 sets of clothes", "Sunglasses + sunscreen", "Lip balm", "Torch", "Personal medicines", "ID card (original)"],
    plan: [
      ["Leave for Manali", "Group meets, safety briefing, overnight train towards Chandigarh."],
      ["Drive up to Manali", "Road journey up the Beas valley. Check in at our Vashisht campus, warm dinner."],
      ["First day on snow", "Ski and snowboard basics at Solang with our instructors. Snow safety talk."],
      ["Ski practice & snow walk", "Morning practice on the slopes, afternoon snow walk in the deodar forest."],
      ["Last snow day", "Final ski session and certificates at the campfire."],
      ["Drive down & home", "Drive to Chandigarh and take the train home."],
    ],
    planIsReal: false,
    reach: "We travel together by train to Chandigarh, then by road to Manali. Nearest airport: Bhuntar (Kullu).",
  },
  {
    slug: "astro-adventure-manali",
    name: "Astro Adventure Trekking Camp",
    region: "across-india",
    state: "Himachal Pradesh",
    type: "Trek",
    days: 10,
    nights: 9,
    altitude: "4,000 m",
    difficulty: "Moderate",
    price: 18000,
    img: "cna/manali/11",
    gallery: ["cna/manali/05", "cna/manali/03", "cna/manali/09", "cna/manali/10", "cna/manali/11"],
    months: ["Apr", "May", "Jun", "Oct"],
    start: "Ahmedabad",
    activities: ["Astronomy sessions", "Trekking to Bhrigu lake", "Rock climbing & rappelling", "River crossing", "River rafting", "Nature education", "Digital detox"],
    campus: "manali",
    featured: true,
    summary: "Trekking, rafting, climbing and night-sky sessions in Manali. The Adventure Olympiad scholarship camp.",
    overview: "Manali’s name is linked with Manu, the sage of the great flood legend, and its valley sits close to the snowline. This camp mixes adventure with science: treks up to the Bhrigu lake region, rock climbing, rappelling, river crossing and rafting by day, and telescope sessions under dark mountain skies by night. Phones stay away: it is a digital detox camp, run by instructors with over 20 years of experience, ending with a certificate.",
    bring: ["8 sets of clothes + night dress", "Light bedding (bed sheet + air pillow)", "5 pairs of socks", "2 warm layers", "Woollen cap + gloves", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent + sunscreen", "ID card (original)"],
    plan: [
      ["Leave for Delhi", "The group meets and leaves by train for Delhi."],
      ["Delhi to Manali", "Reach Delhi and take the evening bus to Manali."],
      ["Jogini falls trek", "Reach Manali in the morning. After breakfast, a trek to Jogini waterfall, lunch near the Vashisht temple, evening in the market."],
      ["Solang valley", "Jeep to the high road towards Rohtang (permits and snow permitting) and Solang valley, with a trek to Anjani Mahadev. Back to Manali."],
      ["Climbing day", "Hadimba and Manu temples, then rock climbing, rappelling and river crossing with our instructors."],
      ["Bhrigu lake trek", "Trek towards Bhrigu lake (about 4,400 m) with a night halt at a high camp near 4,000 m. Pandava caves on the way back."],
      ["Rafting & Kullu", "River rafting on the Beas, then Kullu market and a visit to a shawl workshop to see how it is made."],
      ["Manali to Delhi", "Bus back to Delhi."],
      ["Train home", "Reach Delhi and take the afternoon train home."],
      ["Reach home", "Arrive home with a certificate and a lot of stories."],
    ],
    planIsReal: true,
    reach: "We travel together from Ahmedabad by train to Chandigarh, then by road to Manali. Nearest airport: Bhuntar (Kullu).",
  },
  {
    slug: "ladakh-trek",
    name: "Ladakh Trek",
    region: "across-india",
    state: "Ladakh",
    type: "Trek",
    days: 10,
    nights: 9,
    altitude: "5,000 m",
    difficulty: "Challenging",
    price: null,
    img: "stock/ladakh-trek",
    gallery: [],
    months: ["Jun", "Jul", "Aug"],
    start: "Ahmedabad",
    activities: ["High-altitude trekking", "Camping", "Star gazing"],
    campus: null,
    featured: false,
    summary: "Cold desert valleys, high passes and monasteries on the roof of India.",
    overview: null,
    bring: null,
    plan: [
      ["Fly to Leh", "Arrive in Leh (3,500 m). Full rest. No walking around on day one."],
      ["Acclimatise in Leh", "Short slow walks: Shanti Stupa and the old town."],
      ["Indus valley & monasteries", "Easy hike near the Indus and a visit to a monastery. Gear check."],
      ["Drive to trailhead", "Drive to the start point, short trek to the first camp."],
      ["Trek: river valley", "Walk along a high river valley to a village camp."],
      ["Trek: high pass", "Big day over the pass. Wide views of the Ladakh ranges."],
      ["Trek out", "Descend to the road head, drive back to Leh."],
      ["Khardung La", "Day trip to one of the highest motorable passes, or rest."],
      ["Buffer day", "Kept free for weather. Market walk in Leh."],
      ["Fly home", "Morning flight back."],
    ],
    planIsReal: false,
    reach: "Fly to Leh (via Delhi). Two full rest days in Leh are a must before trekking at this height.",
  },
  {
    slug: "grand-uttaranchal-trek",
    name: "Grand Uttaranchal Trek",
    region: "across-india",
    state: "Uttarakhand",
    type: "Trek",
    days: 7,
    nights: 6,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/uttaranchal/01",
    gallery: ["cna/uttaranchal/04", "cna/uttaranchal/03", "cna/uttaranchal/02", "cna/uttaranchal/01", "cna/uttaranchal/06", "cna/uttaranchal/05", "cna/uttaranchal/07"],
    months: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    start: "Ahmedabad",
    activities: ["River rafting", "Neelkanth trek", "Jeep safari", "Hill walks"],
    campus: null,
    featured: false,
    summary: "Rafting on the Ganga, the Neelkanth trek, Mussoorie and a jungle safari at Rajaji.",
    overview: "Uttarakhand, Dev Bhumi, the land of the gods: fresh mountain air, clear rivers and simple village life at the foot of the Himalaya. This trip rafts 12 km of the Ganga from Shivpuri to Rishikesh, treks up to the Neelkanth temple, walks the hill town of Mussoorie and ends with an early-morning jeep safari in Rajaji National Park.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Train to Haridwar", "The group leaves by train."],
      ["Haridwar", "Arrive in the afternoon. Haridwar sightseeing."],
      ["Rafting to Rishikesh", "Raft 12 km down the Ganga from Shivpuri (about 3 hours), then Rishikesh."],
      ["Neelkanth trek", "Trek to Neelkanth with packed lunch and back to Rishikesh."],
      ["Mussoorie", "Drive to Mussoorie for sightseeing."],
      ["Rajaji safari", "Early jeep safari in Rajaji National Park (Chilla), then Haridwar station."],
      ["Reach home", "Arrive home at night."],
    ],
    planIsReal: true,
    reach: "We travel together from Ahmedabad by train to Haridwar, then by road into the Garhwal hills.",
  },
  {
    slug: "nainital-almora-binsar",
    name: "Nainital, Almora & Binsar",
    region: "across-india",
    state: "Uttarakhand",
    type: "Camp",
    days: 10,
    nights: 9,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/nainital/02",
    gallery: ["cna/nainital/02", "cna/nainital/01", "cna/nainital/04", "cna/nainital/03", "cna/nainital/07", "cna/nainital/05", "cna/nainital/06"],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    start: "Ahmedabad",
    activities: ["Trekking", "Rock climbing", "Rappelling", "Bird watching", "Jungle safari", "Campfire"],
    campus: null,
    featured: false,
    summary: "A camp in the Binsar forests at about 2,100 m, Nainital lake and a safari in Corbett.",
    overview: "Binsar, once the capital of the Chand kings near the old silk route, sits at about 7,000 ft in the Kumaon Himalaya. Quiet oak forests, mountain herbs and big Himalayan views make it a perfect base for young adventurers: treks, rock climbing and rappelling from our campsite. The trip ends with Nainital lake and a jungle safari in Corbett National Park.",
    bring: ["8 sets of clothes + night dress", "Light bedding (bed sheet + air pillow)", "5 pairs of socks", "2 warm layers", "Woollen cap + gloves", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Mosquito repellent + sunscreen", "ID card (original)"],
    plan: [
      ["Train to Delhi", "The group leaves by train for Delhi."],
      ["Delhi to Kathgodam", "Reach Delhi and take the train to Kathgodam."],
      ["Campsite", "Reach the campsite. Night at camp."],
      ["Binsar trek", "Day trek to Binsar. Night at camp."],
      ["Rock day", "Rock climbing and a trek. Night at camp."],
      ["Nainital", "Drive to Nainital for local sightseeing. Night in a hotel."],
      ["Corbett safari", "Jungle safari in Corbett National Park."],
      ["Train to Delhi", "Leave for Delhi by train."],
      ["Train home", "Leave Delhi for Rajkot."],
      ["Reach Rajkot", "Arrive at Rajkot."],
    ],
    planIsReal: true,
    reach: "Train from Ahmedabad to Kathgodam, then by road. Nearest airport: Pantnagar.",
  },
  {
    slug: "leh-ladakh-circuit",
    name: "Leh Ladakh Circuit",
    region: "across-india",
    state: "Ladakh",
    type: "Nature Trail",
    days: 8,
    nights: 7,
    altitude: "5,300 m",
    difficulty: "Moderate",
    price: null,
    img: "cna/ladakh-jammu-kashmir/07",
    gallery: ["cna/ladakh-jammu-kashmir/04", "cna/ladakh-jammu-kashmir/02", "cna/ladakh-jammu-kashmir/03", "cna/ladakh-jammu-kashmir/01", "cna/ladakh-jammu-kashmir/06", "cna/ladakh-jammu-kashmir/05", "cna/ladakh-jammu-kashmir/07"],
    months: ["Jun", "Jul", "Aug", "Sep"],
    start: "Ahmedabad",
    activities: ["High passes", "Lake camps", "Monastery visits"],
    campus: null,
    featured: false,
    summary: "Khardung La, Nubra dunes and the blue of Pangong lake.",
    overview: "Ladakh lies between the Great Himalaya and the Karakoram, from about 2,750 m at Kargil to over 7,600 m at Saser Kangri. Summers are short and bright; winters drop to minus 20 °C even in Leh. Our circuit crosses high passes, the Nubra dunes and the blue water of Pangong. (Duration and plan to be confirmed.)",
    bring: null,
    plan: [
      ["Fly to Leh", "Arrive and rest. Altitude needs respect."],
      ["Leh local", "Shanti Stupa, old town and market walk."],
      ["Over Khardung La to Nubra", "Cross the high pass to Nubra valley. Hunder sand dunes."],
      ["Nubra valley", "Diskit monastery and a walk in the dunes."],
      ["To Pangong lake", "Drive along the Shyok river to Pangong. Lakeside camp."],
      ["Back via Chang La", "Sunrise at the lake, drive back to Leh."],
      ["Sham valley", "Indus–Zanskar confluence and Magnetic Hill."],
      ["Fly home", "Morning flight back."],
    ],
    planIsReal: false,
    reach: "Fly to Leh (via Delhi). Day one is full rest for altitude.",
  },
  {
    slug: "shimla-manali-amritsar",
    name: "Shimla, Manali & Amritsar",
    region: "across-india",
    state: "Himachal & Punjab",
    type: "Nature Trail",
    days: 8,
    nights: 7,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/upcomingtours/14",
    gallery: ["cna/upcomingtours/14"],
    months: ["Apr", "May", "Jun", "Oct"],
    start: "Ahmedabad",
    activities: ["Nature walks", "River side camp", "Heritage walk"],
    campus: null,
    featured: false,
    summary: "Hill towns, the Beas valley and an evening at the Golden Temple.",
    overview: "Hill towns, river valleys and the Golden Temple: Shimla’s ridge, the Kullu and Beas valleys around Manali, and an evening at Amritsar.",
    bring: null,
    plan: [
      ["Leave by train", "Overnight train to Chandigarh."],
      ["Shimla", "Drive up to Shimla. Evening on the Ridge."],
      ["To Manali", "Scenic drive through the Kullu valley."],
      ["Solang valley", "Meadows and mountain views. Hadimba forest walk."],
      ["Manali & Vashisht", "Riverside walk and Vashisht village."],
      ["To Amritsar", "Long drive down to the plains."],
      ["Golden Temple & Wagah", "Morning at the Golden Temple, evening Wagah border ceremony. Train home."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: false,
    reach: "Train to Chandigarh, then by road. Return by train from Amritsar.",
  },
  {
    slug: "kullu-shimla-manali",
    name: "Kullu, Shimla & Manali",
    region: "across-india",
    state: "Himachal Pradesh",
    type: "Nature Trail",
    days: 6,
    nights: 5,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/upcomingtours/15",
    gallery: ["cna/upcomingtours/15"],
    months: ["Apr", "May", "Jun", "Oct", "Dec"],
    start: "Ahmedabad",
    activities: ["River rafting", "Nature walks", "Snow point"],
    campus: "manali",
    featured: false,
    summary: "Apple valleys, pine forests and a rafting day on the Beas.",
    overview: "A classic Himachal loop: Shimla’s hill walks, a rafting day on the Beas in Kullu and the snow and meadows of Solang near Manali.",
    bring: null,
    plan: [
      ["Leave by train", "Overnight train to Chandigarh."],
      ["Shimla", "Drive up to Shimla. Evening on the Ridge and a hill walk."],
      ["Kullu & rafting", "Drive to the Kullu valley. River rafting on the Beas."],
      ["Solang valley", "Meadows and snow point near Manali (season permitting)."],
      ["Drive down", "Drive to Chandigarh, overnight train."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: false,
    reach: "Train to Chandigarh, then by road.",
  },
  {
    slug: "kullu-manali-dalhousie",
    name: "Kullu, Manali & Dalhousie",
    region: "across-india",
    state: "Himachal Pradesh",
    type: "Nature Trail",
    days: 6,
    nights: 5,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/upcomingtours/16",
    gallery: ["cna/upcomingtours/16"],
    months: ["Apr", "May", "Jun", "Oct"],
    start: "Ahmedabad",
    activities: ["Nature walks", "Meadow hikes", "River rafting"],
    campus: "manali",
    featured: false,
    summary: "From the Kullu valley to the meadows of Khajjiar near Dalhousie.",
    overview: "From the Kullu valley and Manali to Dalhousie and the deodar-ringed meadow of Khajjiar, often called the mini Switzerland of India.",
    bring: null,
    plan: [
      ["Leave by train", "Overnight train to Chandigarh."],
      ["Kullu & Manali", "Drive up the Kullu valley to Manali."],
      ["Solang valley", "Meadows and mountain views."],
      ["To Dalhousie", "Long scenic drive west to Dalhousie."],
      ["Khajjiar & leave", "The famous meadow ringed by deodar forest, then drive to Pathankot for the train."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: false,
    reach: "Train to Chandigarh. Return by train from Pathankot.",
  },
  {
    slug: "nainital-mussoorie-corbett",
    name: "Nainital, Mussoorie & Corbett",
    region: "across-india",
    state: "Uttarakhand",
    type: "Nature Trail",
    days: 9,
    nights: 8,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/upcomingtours/17",
    gallery: ["cna/upcomingtours/17"],
    months: ["Mar", "Apr", "May", "Oct", "Nov"],
    start: "Ahmedabad",
    activities: ["Jungle safari", "Nature walks", "Bird watching"],
    campus: null,
    featured: false,
    summary: "Lake towns, hill walks and tiger country at Jim Corbett.",
    overview: "Two lake-and-hill towns and a tiger forest: Mussoorie, Jim Corbett National Park and Nainital.",
    bring: null,
    plan: [
      ["Leave by train", "Overnight train to Dehradun."],
      ["Mussoorie", "Drive up to Mussoorie. Camel’s Back Road walk."],
      ["Mussoorie nature day", "Waterfall and viewpoint walks."],
      ["To Jim Corbett", "Drive to Corbett. Riverside evening."],
      ["Jungle safari", "Morning safari, nature walk by the Kosi river."],
      ["Nainital", "Drive to Nainital. Boat ride on the lake."],
      ["Nainital hills", "Walk to a Himalayan viewpoint above the town."],
      ["Drive down", "Drive to Kathgodam, overnight train."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: false,
    reach: "Train to Dehradun. Return by train from Kathgodam.",
  },
  {
    slug: "mount-abu",
    name: "Mount Abu",
    region: "across-india",
    state: "Rajasthan",
    type: "Camp",
    days: 3,
    nights: 2,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/abu/02",
    gallery: ["cna/abu/01", "cna/abu/03", "cna/abu/04", "cna/abu/02", "cna/abu/06", "cna/abu/05", "cna/abu/07"],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    start: "Rajkot",
    activities: ["Rock climbing", "Rappelling", "Jeep safari", "Lake & sunset walks"],
    campus: null,
    featured: false,
    summary: "Rock climbing at Toad Rock, Nakki lake and sunsets in Rajasthan’s only hill station.",
    overview: "Mount Abu sits at about 1,220 m in the Aravalli hills: a green, cool island in dry Rajasthan and the only hill station in the state. Guru Shikhar, the highest point of the Aravallis, the Dilwara Jain temples, Nakki lake and forested slopes make it a great short camp. Toad Rock is our rock-climbing and rappelling wall.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Bus to Mount Abu", "Early morning bus (5 am), breakfast and lunch on the highway. Arrive, freshen up, evening market walk and dinner."],
      ["Rock day & sunset", "Jeep safari to the Dilwara temples and Guru Shikhar, then rock climbing and rappelling at Toad Rock. Evening at Nakki lake and Sunset Point."],
      ["Return", "Breakfast and travel back home."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "rajasthan-heritage",
    name: "Rajasthan Heritage Tour",
    region: "across-india",
    state: "Rajasthan",
    type: "Nature Trail",
    days: 8,
    nights: 7,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/rajasthan/05",
    gallery: ["cna/rajasthan/01", "cna/rajasthan/02", "cna/rajasthan/04", "cna/rajasthan/05", "cna/rajasthan/07", "cna/rajasthan/03", "cna/rajasthan/06"],
    months: ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    start: "Rajkot",
    activities: ["Desert National Park", "Forts & palaces", "Heritage walks", "Evening folk programme"],
    campus: null,
    featured: false,
    summary: "Udaipur’s lakes, Jaipur’s forts, Jodhpur and the golden fort of Jaisalmer.",
    overview: "A journey across Rajasthan: the lake city of Udaipur, Jaipur the Pink City (founded in 1727 by Sawai Jai Singh II), the blue city of Jodhpur and the living golden fort of Jaisalmer, at the edge of the Thar desert. Between forts and old havelis we visit the Desert National Park and end with an evening folk programme.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Train to Udaipur", "The group leaves by train."],
      ["Udaipur", "Arrive and explore the lake city."],
      ["To Jaipur", "Travel to Jaipur and rest."],
      ["Jaipur", "Amber fort, Jal Mahal, Albert Hall museum, Birla planetarium, Lakshmi Narayan temple and Amar Jawan Jyoti. Night journey to Jodhpur."],
      ["Jodhpur", "Jodhpur sightseeing, then on to Jaisalmer."],
      ["Jaisalmer", "Jaisalmer fort, Nathmal and Salim Singh havelis, the Desert National Park and an evening folk programme."],
      ["Leave for home", "Journey home."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "lonavala",
    name: "Lonavala",
    region: "across-india",
    state: "Maharashtra",
    type: "Camp",
    days: 6,
    nights: 5,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/lonavala/02",
    gallery: ["cna/lonavala/02", "cna/lonavala/03", "cna/lonavala/01", "cna/lonavala/07", "cna/lonavala/04", "cna/lonavala/06", "cna/lonavala/05"],
    months: ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb"],
    start: "Rajkot",
    activities: ["Fort trek", "Hill treks", "Dam & lake walks", "Nature education", "Boating"],
    campus: null,
    featured: false,
    summary: "Forts, dams and green Sahyadri treks around the hill town of Lonavala.",
    overview: "Lonavala, about 625 m up in the Sahyadri hills, is known as the jewel of the Western Ghats. Heavy monsoon rains from June to September turn every slope into a waterfall, and the cool winters are perfect for treks. We climb Tiger Hill and Korigad fort, learn about nature around Pawna lake and walk the hills above the town.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Lonavala & Tiger Hill", "Wax museum, Bhushi dam and the Tiger Hill trek."],
      ["Pawna lake", "Pawna dam with a nature education session, trekking and boating."],
      ["Korigad fort", "Korigad fort, Tungarli dam and the Tungarli hill trek."],
      ["Adventure park", "Della adventure park (rides are self-paid) and a ghat viewpoint drive."],
      ["Lonavala lake & leave", "Lonavala hills and lake, then the journey home."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "panchgani-mahabaleshwar",
    name: "Panchgani & Mahabaleshwar",
    region: "across-india",
    state: "Maharashtra",
    type: "Camp",
    days: 6,
    nights: 5,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/lonavala/01",
    gallery: ["cna/lonavala/01", "cna/panchgani/03", "cna/panchgani/02", "cna/panchgani/06", "cna/panchgani/07", "cna/panchgani/05", "cna/panchgani/04"],
    months: ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb"],
    start: "Rajkot",
    activities: ["Jungle treks", "Table Land walk", "Valley viewpoints", "River & dam walks"],
    campus: null,
    featured: false,
    summary: "Five hills, the Krishna valley and the viewpoints of Mahabaleshwar.",
    overview: "Panchgani takes its name from the five hills around it. At 1,334 m it sits just below Mahabaleshwar, on a winding road with views of the Krishna river on one side and the coastal plains on the other. Old British buildings, Parsi houses and boarding schools give it a quiet charm. We walk its jungle trails, the Table Land plateau and the viewpoints of Mahabaleshwar.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Train to Mumbai", "The group leaves by train for Mumbai."],
      ["To Panchgani", "Reach Mumbai, freshen up, breakfast and drive to Panchgani."],
      ["Panchgani", "Krishna river views, Dhom dam, a jungle trek and the old church."],
      ["Mahabaleshwar", "Viewpoints, the river and dam, a trek and the temple."],
      ["Back to Mumbai", "Drive to Mumbai and take the train home."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "pachmarhi",
    name: "Pachmarhi",
    region: "across-india",
    state: "Madhya Pradesh",
    type: "Camp",
    days: 6,
    nights: 5,
    altitude: null,
    difficulty: "Moderate",
    price: null,
    img: "cna/pachmarhi/02",
    gallery: ["cna/pachmarhi/02", "cna/pachmarhi/04", "cna/pachmarhi/03", "cna/pachmarhi/05", "cna/pachmarhi/06", "cna/pachmarhi/07"],
    months: ["Aug", "Sep", "Nov", "Dec"],
    start: "Rajkot",
    activities: ["Forest treks", "Waterfalls", "Caves", "Wildlife"],
    campus: null,
    featured: false,
    summary: "Forest treks, waterfalls and caves in the Satpura hills of Madhya Pradesh.",
    overview: "Pachmarhi sits inside the Satpura forests of Madhya Pradesh: thick forest, deep ravines, rare orchids and wildlife such as leopards, wild boar, peacocks and langurs. Every day here is a trek, to waterfalls, pools, caves and hilltop viewpoints like Dhoopgarh. Camps run in August (Janmashtami holidays), November and December.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Bus & train", "Early bus to Ahmedabad, afternoon train to Pipariya."],
      ["Into the hills", "Reach Pipariya by 10:30 am, bus to Pachmarhi. After lunch, treks to Priyadarshini point, Jamuna and Handi Khoh."],
      ["Waterfall treks", "Treks to Apsara Vihar, Rajat Prapat, Jalavataran and Sundar Kund."],
      ["Hilltops & caves", "Jata Shankar cave, Dhoopgarh, Reechgarh and Chauragarh."],
      ["Leave for home", "Bus back to Pipariya and the evening train home."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "jabalpur-kanha",
    name: "Jabalpur, Bhedaghat & Kanha",
    region: "across-india",
    state: "Madhya Pradesh",
    type: "Camp",
    days: 6,
    nights: 5,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/jabalpur_bhedaghat/03",
    gallery: ["cna/jabalpur_bhedaghat/02", "cna/jabalpur_bhedaghat/01", "cna/jabalpur_bhedaghat/07", "cna/jabalpur_bhedaghat/05", "cna/jabalpur_bhedaghat/04", "cna/jabalpur_bhedaghat/03", "cna/jabalpur_bhedaghat/06"],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    start: "Rajkot",
    activities: ["Jungle safari", "Bird watching", "Marble rocks boat ride", "Waterfalls"],
    campus: null,
    featured: false,
    summary: "Kanha’s tiger forests and the marble gorge of the Narmada at Bhedaghat.",
    overview: "Kanha is Kipling country: the sal forests and meadows here inspired The Jungle Book. It is one of India’s best tiger reserves and the last home of the hard-ground swamp deer (barasingha), with around 175 kinds of birds. On the way back we stop at Bhedaghat, where the Narmada flows through a gorge of white marble. (Kanha’s core zone closes in the monsoon.)",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Train to Jabalpur", "Meet at the railway station and leave for Jabalpur."],
      ["To Kanha", "Reach Jabalpur and drive 164 km to Kanha. Check in and overnight."],
      ["Kanha safari", "Full day at Kanha with a morning or evening jungle safari by canter."],
      ["Bhedaghat", "Drive back to Jabalpur (164 km). After lunch, the Narmada and the marble rocks at Bhedaghat."],
      ["Train home", "Leave Jabalpur for home."],
      ["Reach home", "Arrive at Rajkot railway station."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "goa",
    name: "Goa",
    region: "across-india",
    state: "Goa",
    type: "Nature Trail",
    days: 8,
    nights: 7,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/goa/06",
    gallery: ["cna/goa/02", "cna/goa/01", "cna/goa/04", "cna/goa/07", "cna/goa/06", "cna/goa/05"],
    months: ["Jan", "Feb", "Mar", "Jun", "Jul"],
    start: "Rajkot",
    activities: ["Jungle trek to Dudhsagar falls", "Rock climbing", "Rappelling", "Bird watching", "Beaches", "Campfire"],
    campus: null,
    featured: false,
    summary: "Beaches, forts, old churches and a jungle trek to Dudhsagar falls.",
    overview: "Goa is more than its beaches. East meets west here in temples and old churches, forts on the sea and a history that goes back more than 2,000 years. Our camp walks the long beaches of north and south Goa, visits Aguada fort and Old Goa, and heads inland for a jungle trek to the four-tiered Dudhsagar waterfall. Camps run in June-July and after 20 January.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Train to Goa", "The group leaves by train."],
      ["Madgaon to Panaji", "Arrive at Madgaon, bus to Panaji (2 hours). Lunch and rest, nearby sights and an evening river cruise."],
      ["North Goa", "Arambol, Vagator, Anjuna, Calangute, Baga and Candolim beaches, and Aguada fort. Packed lunch."],
      ["South Goa", "Bogmalo, Majorda, Utorda, Colva and Benaulim beaches, plus Old Goa’s church and museum. Packed lunch."],
      ["Dudhsagar falls", "Jungle trek to the Dudhsagar waterfall. Evening at Dona Paula, Miramar and the science museum."],
      ["Panaji", "Panaji city walk, shopping and a free day."],
      ["Leave for home", "Early morning departure after breakfast."],
      ["Reach home", "Arrive home in the evening."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "kerala",
    name: "Kerala",
    region: "across-india",
    state: "Kerala",
    type: "Nature Trail",
    days: 9,
    nights: 8,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/kerala/06",
    gallery: ["cna/kerala/04", "cna/kerala/02", "cna/kerala/03", "cna/kerala/06", "cna/kerala/01", "cna/kerala/07"],
    months: ["Oct", "Nov", "Dec", "Jan", "Feb"],
    start: "Rajkot",
    activities: ["Tea garden walks", "Eravikulam National Park", "Spice plantation", "Lake boating", "Backwaters"],
    campus: null,
    featured: false,
    summary: "Fort Kochi, the tea hills of Munnar, Thekkady’s spice forest and the backwaters of Alleppey.",
    overview: "Kerala grew rich on the spice trade, and traders from Greece, Rome, Arabia, China and Europe all left their mark here. Between the Arabian Sea and the Western Ghats, the state packs tea hills, wildlife forests, 44 rivers and endless backwaters into a narrow strip. Our trip moves from old Fort Kochi up to Munnar, through the spice forests of Thekkady and down to the backwaters of Alleppey.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Leave for Kochi", "The group leaves for Kochi."],
      ["Arrive Kochi", "Reach Kochi at night and check in."],
      ["Fort Kochi", "Fort Kochi, Mattancherry, the Jewish synagogue, Chinese fishing nets, Santa Cruz Basilica and St. Francis Church."],
      ["To Munnar", "Drive to Munnar (5 hours) past waterfalls and tea plantations."],
      ["Munnar", "Mattupetty dam, Kundala lake, Eravikulam National Park and Munnar town."],
      ["Thekkady", "Drive to Thekkady (4 hours). Spice plantation and a boat ride on the lake."],
      ["Alleppey", "Drive to Alleppey (5 hours). Alleppey beach and a coir-making workshop."],
      ["Leave for home", "Return journey from Kochi."],
      ["Reach home", "Arrive home at night."],
    ],
    planIsReal: true,
    reach: "Fly or train to Kochi, then by road.",
  },
  {
    slug: "karnataka",
    name: "Karnataka",
    region: "across-india",
    state: "Karnataka",
    type: "Nature Trail",
    days: 10,
    nights: 9,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/karnataka/05",
    gallery: ["cna/karnataka/01", "cna/karnataka/07", "cna/karnataka/05", "cna/karnataka/03", "cna/karnataka/06", "cna/karnataka/04"],
    months: ["Oct", "Nov", "Dec", "Jan"],
    start: "Rajkot",
    activities: ["Rock climbing at Ramanagara", "Zip line & bouldering", "Tent camping", "Waterfalls", "Wildlife sanctuary", "Trekking"],
    campus: null,
    featured: false,
    summary: "Rock climbing and a tent night at Ramanagara, Mysore palace and the coffee hills of Coorg.",
    overview: "This trip starts in Bengaluru, the garden city, and quickly heads for the rocks: Ramanagara’s granite hills are one of South India’s best climbing spots. From there we visit royal Mysore and spend three days in Coorg’s coffee hills, with waterfalls, Nagarhole wildlife sanctuary, the source of the Kaveri at Talakaveri and a forest trek to Nishani Motte.",
    bring: ["10 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent + sunscreen"],
    plan: [
      ["Leave by train", "The group leaves for Bengaluru."],
      ["On the train", "A long train day across India."],
      ["Bengaluru", "Arrive and rest. ISKCON temple and the Visvesvaraya science museum."],
      ["Ramanagara rock day", "Rappelling, chimney climbing, zip line, bouldering and face climbing. Campfire and a night in tents."],
      ["Mysore", "Drive to Mysore (3 hours): zoo, Chamundi hill, the palace and KRS dam. Late night arrival in Coorg."],
      ["Coorg", "The Golden Temple at Bylakuppe, a waterfall, Omkareshwara temple and Raja’s Seat."],
      ["Waterfalls & wildlife", "Iruppu falls, Nagarhole wildlife sanctuary and Nalknad palace."],
      ["Talakaveri & trek", "Talakaveri and the trek to Nishani Motte, then drive back to Bengaluru station."],
      ["On the train", "Train journey home."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: true,
    reach: "Fly or train to Bengaluru / Mysuru, then by road.",
  },
  {
    slug: "odisha",
    name: "Odisha",
    region: "across-india",
    state: "Odisha",
    type: "Nature Trail",
    days: 10,
    nights: 9,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/odisha/06",
    gallery: ["cna/kerala/02", "cna/odisha/05", "cna/odisha/06", "cna/odisha/03", "cna/odisha/01", "cna/odisha/04", "cna/odisha/07"],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    start: "Bhubaneswar",
    activities: ["Mangrove boat safari", "Dolphin spotting", "Bird sanctuary", "Temple heritage", "Beaches"],
    campus: null,
    featured: false,
    summary: "Bhitarkanika mangroves, Chilika’s dolphins, Konark and Puri on the Bay of Bengal.",
    overview: "Odisha runs along the Bay of Bengal, rising inland to the Eastern Ghats. It is temple country, with the old shrines of Bhubaneswar, Puri’s Jagannath temple and the Sun Temple at Konark, and wild country too: the crocodile creeks of Bhitarkanika, Chilika lake with its dolphins and birds, and the hot springs of Taptapani.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Leave by train", "The group leaves for Bhubaneswar."],
      ["On the train", "Train journey."],
      ["Bhitarkanika", "Arrive Bhubaneswar, drive to Bhitarkanika National Park. Boat ride into the mangrove creeks to see wildlife and birds."],
      ["Bhubaneswar & Puri", "The 6th-12th century temples of Bhubaneswar (Mukteswar, Rajarani and more) and the Dhauli stupa. Evening drive to Puri."],
      ["Konark & Chilika", "Jagannath temple, the Sun Temple at Konark, then Satapada on Chilika lake for a boat ride to see dolphins where the lake meets the sea."],
      ["Birds & Taptapani", "Early boat to the bird sanctuary and Kalijai island, then drive to the hill resort of Taptapani."],
      ["Gopalpur & caves", "Gopalpur-on-Sea, the Khandagiri and Udayagiri Jain caves and Nandankanan zoo."],
      ["Lingaraj & leave", "Lingaraj and Vaital temples, the tribal museum, then the train home."],
      ["On the train", "Train journey."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: true,
    reach: "Fly or train to Bhubaneswar.",
  },
  {
    slug: "sikkim-trek",
    name: "Sikkim Trek",
    region: "north-east",
    state: "Sikkim",
    type: "Trek",
    days: 9,
    nights: 8,
    altitude: "3,750 m",
    difficulty: "Easy",
    price: null,
    img: "cna/sikkim/03",
    gallery: ["cna/sikkim/04", "cna/sikkim/05", "cna/sikkim/01", "cna/sikkim/02", "cna/sikkim/03", "cna/sikkim/07", "cna/sikkim/06"],
    months: ["Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    start: "Rajkot",
    activities: ["Nature walks", "Tsomgo lake", "River rafting", "Himalayan zoo"],
    campus: null,
    featured: true,
    summary: "Gangtok, the glacial Tsomgo lake at 3,750 m and rafting on the Teesta.",
    overview: "Sikkim is a small mountain state in the eastern Himalaya, rising from about 300 m to 8,586 m at Kanchenjunga, India’s highest peak. It became India’s 22nd state in 1975 and is home to the Lepcha, Bhutia and Nepali communities. From Gangtok we walk through the Himalayan Zoological Park, drive up to the glacial Tsomgo lake and raft a stretch of the Teesta on the way down.",
    bring: ["8 sets of clothes + night dress", "5 pairs of socks", "2 warm layers", "Woollen cap + gloves", "Rain jacket", "Torch", "Personal medicines", "Shoulder bag + water bottle", "Sunglasses + sunscreen", "ID card (original)"],
    plan: [
      ["Leave by train", "The group leaves for New Jalpaiguri."],
      ["On the train", "Train journey."],
      ["Gangtok", "Reach and drive up to Gangtok."],
      ["Gangtok sights", "Gangtok sightseeing."],
      ["Himalayan Zoological Park", "Nature walk in the Himalayan Zoological Park."],
      ["Tsomgo lake", "Day excursion to Tsomgo lake (3,750 m) and back."],
      ["Rafting & leave", "Drive to NJP with a short rafting stretch on the way, then the train."],
      ["On the train", "Train journey."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: true,
    reach: "Fly or train to Bagdogra / New Jalpaiguri, then by road to Sikkim.",
  },
  {
    slug: "everest-base-camp",
    name: "Everest Base Camp Trek",
    region: "outside-india",
    state: "Nepal",
    type: "Trek",
    days: 18,
    nights: 17,
    altitude: "5,364 m",
    difficulty: "Challenging",
    price: null,
    img: "cna/everest_base_camp/05",
    gallery: ["cna/everest_base_camp/04", "cna/everest_base_camp/02", "cna/everest_base_camp/03", "cna/everest_base_camp/01", "cna/everest_base_camp/07", "cna/everest_base_camp/06", "cna/everest_base_camp/05"],
    months: ["Sep", "Oct"],
    start: "Rajkot",
    activities: ["High-altitude trekking", "Kala Patthar sunrise", "Sherpa villages", "Monasteries"],
    campus: null,
    featured: true,
    summary: "The classic Khumbu trek to Everest Base Camp (5,364 m) and the view from Kala Patthar (5,545 m).",
    overview: "The trek to Everest Base Camp walks through the Khumbu valley of Nepal: Sherpa villages, Buddhist monasteries like Tengboche, and some of the highest peaks on earth. Base Camp sits on a glacier moraine at 5,364 m, used by climbers on their way up Everest (8,848 m). The highlight is the dawn climb to Kala Patthar (5,545 m), with close views of Everest, Pumori, Nuptse and Lhotse. Rest days are built in for acclimatisation.",
    bring: ["Trek shoes (broken in)", "Thermals, fleece + down jacket", "Woollen cap + gloves", "5 pairs of socks", "8 sets of clothes", "Sleeping bag liner", "Torch / headlamp", "Personal medicines", "Sunglasses + sunscreen", "Water bottles (2)", "Passport or voter ID (original)"],
    plan: [
      ["Fly to Kathmandu", "Fly to Delhi, then on to Kathmandu."],
      ["Kathmandu", "Half-day guided city tour and trek preparation."],
      ["Lukla & Phakding", "Mountain flight to Lukla (35 min), then a 3-4 hour walk to Phakding (2,652 m)."],
      ["To Namche Bazaar", "Climb to Namche Bazaar (3,440 m), 5-6 hours."],
      ["Rest day in Namche", "Acclimatisation day with a short walk."],
      ["To Khumjung", "Walk to Khumjung (3,640 m), about 4 hours."],
      ["To Tengboche", "Walk to the Tengboche monastery (3,870 m), 4-5 hours."],
      ["To Dingboche", "Into the high valley at Dingboche (4,430 m), 5-6 hours."],
      ["Rest day in Dingboche", "Acclimatisation: climb high, sleep low."],
      ["To Dughla", "Walk to Dughla (4,610 m), 4-5 hours."],
      ["To Lobuche", "Walk to Lobuche (4,960 m), 2-4 hours."],
      ["Everest Base Camp", "Lobuche to Gorak Shep (5,110 m), on to Everest Base Camp (5,364 m) and back to Gorak Shep, 6-7 hours."],
      ["Kala Patthar", "Dawn climb to Kala Patthar (5,545 m), then down to Pheriche (4,440 m), 7-8 hours."],
      ["Back to Namche", "Pheriche to Namche Bazaar, 5-6 hours."],
      ["To Lukla", "Namche via Phakding to Lukla, 6-7 hours."],
      ["Fly to Kathmandu", "Mountain flight back (weather permitting)."],
      ["Fly home", "Kathmandu to Delhi, and on home."],
      ["Reach home", "Arrive home."],
    ],
    planIsReal: true,
    reach: "Fly to Kathmandu. Indian citizens need a valid passport or voter ID for Nepal. Flights to Lukla depend on weather.",
  },
  {
    slug: "bet-dwarka-marine-camp",
    name: "Marine Camp, Bet Dwarka",
    region: "gujarat",
    state: "Devbhumi Dwarka",
    type: "Camp",
    days: 4,
    nights: 3,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/marinecamp/02",
    gallery: ["cna/marinecamp/03", "cna/marinecamp/01", "cna/marinecamp/02", "cna/marinecamp/06", "cna/marinecamp/07", "cna/marinecamp/04", "cna/marinecamp/05"],
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    start: "Rajkot",
    activities: ["Low-tide marine walk", "Island boat visits", "Bird watching", "Star gazing", "Sea awareness talk", "Scuba diving introduction"],
    campus: "dwarka",
    featured: true,
    summary: "Where CNA began in 1997: low-tide walks among corals, starfish and sea life at the mouth of the Gulf of Kutch.",
    overview: "CNA’s story began here, with the first Marine Camp in December 1997. The camp sits at Bet Dwarka, at the mouth of the Gulf of Kutch, where the sea is clear, calm and safe. At low tide the shore turns into an open-air classroom: corals, starfish, sea anemones and crabs, and on lucky days dolphins and sea turtles. Campers learn about tides, moon phases, marine life, birds and the night sky, and many leave with a lifelong love for the sea.",
    bring: ["3 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent + sunscreen", "Swimming costume"],
    plan: [
      ["Night train to the coast", "The group meets at the station and takes the night train towards Okha and Bet Dwarka."],
      ["Shore trek & temples", "After breakfast, a trek along the seashore with visits to Dandi Hanuman and the Krishna temple. Afternoon: Padma Tirth and another coastal walk."],
      ["Island day", "Boat visits to nearby islands such as Dunni, Churna, Dabdaba and Sindhi. We land only when the weather and tide are safe."],
      ["Marine talk, Dwarka & home", "An expert talk on the sea and marine life, then on to Dwarka for a scuba-diving introduction with trained experts and a visit to the Dwarkadhish temple. Night train home."],
    ],
    planIsReal: true,
    reach: "We travel together from Rajkot by bus to Okha, then by boat to Bet Dwarka.",
  },
  {
    slug: "narara",
    name: "Narara Island Coral Walk",
    region: "gujarat",
    state: "Jamnagar",
    type: "Camp",
    days: 1,
    nights: 0,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/narara/03",
    gallery: ["cna/narara/01", "cna/narara/07", "cna/narara/02", "cna/narara/06", "cna/narara/05", "cna/narara/03", "cna/narara/04"],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    start: "Rajkot",
    activities: ["Low-tide coral walk", "Marine life spotting", "Bird watching", "Coastal walk"],
    campus: null,
    featured: false,
    summary: "A one-day walk on a living coral reef at low tide, inside the Marine National Park.",
    overview: "Narara is one of the few places in the world where you can see a living coral reef without diving. At low tide you walk in knee-deep water and the reef opens up around you: corals, starfish, octopus, sea anemones, puffer fish, crabs and, with luck, sea turtles. The Gulf of Kutch has 42 islands fringed with reefs, mangroves and sandy beaches, which also makes it a great place for birds.",
    bring: ["1 spare set of clothes", "2 pairs of socks", "Light sweater", "Torch", "Personal medicines", "Small bag + water bottle", "Cap + sunglasses", "Sunscreen", "Clothes that can get wet"],
    plan: [
      ["Day trip to the reef", "Early start (5 am), breakfast on the way. Guided low-tide walk on the reef, lunch, then a coastal walk and bird watching. Leave for home around 6 pm."],
    ],
    planIsReal: true,
    reach: "We travel together from Rajkot by bus via Jamnagar.",
  },
  {
    slug: "sasan-gir",
    name: "Sasan Gir Wildlife Camp",
    region: "gujarat",
    state: "Junagadh",
    type: "Camp",
    days: 3,
    nights: 2,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/sasangir/02",
    gallery: ["cna/sasangir/04", "cna/sasangir/05", "cna/sasangir/03", "cna/sasangir/06", "cna/sasangir/02"],
    months: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    start: "Rajkot",
    activities: ["Jungle jeep safari", "Forest trek", "Wildlife watching", "Campfire"],
    campus: null,
    featured: true,
    summary: "Three days in the last wild home of the Asiatic lion: safari, forest walks and campfire nights.",
    overview: "Gir is the only place on earth where Asiatic lions still live in the wild. The national park and sanctuary covers about 1,412 sq km of dry forest in Junagadh and Amreli districts, and has been protected since 1965. Besides lions it shelters around 38 kinds of mammals and about 300 kinds of birds. This camp mixes a jungle safari with forest walks, bird watching and campfire evenings near Talala.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Arrive at Gir", "Reach Sasan Gir by late morning and check in. Afternoon walk around Talala and nearby villages. Dinner and campfire."],
      ["Jungle safari", "Morning jeep safari in the Gir forest (Devalia; permits subject to availability). Afternoon nature trek in the forest area. Campfire night."],
      ["Waterfall, temple & home", "Morning visit to nearby spots such as the Jamjir waterfall (in the monsoon) and the Gayatri temple. Lunch, then travel home."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "osam-hill",
    name: "Osam Hill, Patanvav",
    region: "gujarat",
    state: "Rajkot district",
    type: "Camp",
    days: 1,
    nights: 0,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/osamhill/06",
    gallery: ["cna/osamhill/04", "cna/osamhill/05", "cna/osamhill/06", "cna/osamhill/07"],
    months: ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb"],
    start: "Rajkot",
    activities: ["Hill trek", "Wildlife watching", "Temple visits", "Bhim Kund"],
    campus: null,
    featured: false,
    summary: "A one-day trek on a green hill near Rajkot, with old temples and the Bhim Kund pool.",
    overview: "Osam Hill rises above Patanvav village in Rajkot district. In the monsoon the whole hill turns green and comes alive. Trails lead past the Mataji and Tapkeshwar temples and the Bhim Kund pool, with wide views over the countryside. Open all year, best from July to February, and a perfect first trek for schools and families.",
    bring: ["1 spare set of clothes", "2 pairs of socks", "Light sweater", "Torch", "Personal medicines", "Small bag + water bottle", "Cap + sunglasses", "Sunscreen", "Clothes that can get wet"],
    plan: [
      ["Day trek on Osam Hill", "Leave at 5 am, breakfast on the way. Explore Patanvav, then trek up the hill, visit the temples and Bhim Kund. Lunch, more trails and wildlife spotting. Leave for home around 6 pm."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "hingolgadh-nature-camp",
    name: "Hingolgadh Nature Camp",
    region: "gujarat",
    state: "Rajkot district",
    type: "Camp",
    days: 2,
    nights: 1,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "stock/campus-hingolgadh",
    gallery: [],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    start: "Rajkot",
    activities: ["Bird watching", "Star gazing", "Hiking", "EVS introduction"],
    campus: "hingolgadh",
    featured: false,
    summary: "Hill-fort country near Jasdan: birds at dawn, hikes by day and stars at night. Open all seasons.",
    overview: "Hingolgadh is a nature education sanctuary near Jasdan in Rajkot district, around a hilltop palace. Its dry scrub forest and grasslands are full of birds, which makes it a classic place for nature camps. We spend the day on easy hikes and an EVS session, and the night under the stars.",
    bring: null,
    plan: [
      ["Rajkot to Hingolgadh", "Short drive to Jasdan. Nature walk, EVS session, star gazing night."],
      ["Birds & home", "Dawn bird watching and a hike, back to Rajkot by afternoon."],
    ],
    planIsReal: false,
    reach: null,
  },
  {
    slug: "kutch",
    name: "Kutch Nature Camp",
    region: "gujarat",
    state: "Kutch",
    type: "Camp",
    days: 4,
    nights: 3,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/kucth/01",
    gallery: ["cna/kucth/05", "cna/kucth/01", "cna/kucth/04", "cna/kucth/03", "cna/kucth/02", "cna/kucth/07", "cna/kucth/06"],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    start: "Rajkot",
    activities: ["White Rann", "Wildlife sanctuary", "Heritage walks", "Kutch culture"],
    campus: null,
    featured: false,
    summary: "Salt desert, grasslands, palaces and craft villages in India’s largest district.",
    overview: "Kutch is India’s largest district: salt desert, grasslands, coast and craft villages. The Great and Little Rann are seasonal wetlands that flood and dry every year, and the name Kutch itself means a land that turns wet and dry. The Banni grasslands, Narayan Sarovar sanctuary and the white salt desert make it one of Gujarat’s richest nature and culture trips.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Rajkot to Bhuj", "Bus to Bhuj, the district capital. Afternoon: Hamirsar lake, Kutch Museum, Aina Mahal and the Ramkund step well."],
      ["Bhuj & the west", "Swaminarayan temple, the royal cenotaphs (Chhatardi), Sharad Baug palace and the Koteshwar temple by the sea."],
      ["Narayan Sarovar & White Rann", "Narayan Sarovar wildlife sanctuary, then on to Dhordo for sunset on the white salt desert."],
      ["Beach, palace & home", "Pingleshwar beach, Madreshwar and the Vijay Vilas palace at Mandvi, then travel home."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "saputara",
    name: "Saputara, Dang Forest",
    region: "gujarat",
    state: "Dang",
    type: "Camp",
    days: 5,
    nights: 4,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/saputara/07",
    gallery: ["cna/saputara/01", "cna/saputara/04", "cna/saputara/07", "cna/saputara/06", "cna/saputara/03", "cna/saputara/02"],
    months: ["Jul", "Aug", "Sep"],
    start: "Rajkot",
    activities: ["Forest trek", "Waterfalls", "Vansda National Park", "Caves", "Lake boating"],
    campus: null,
    featured: false,
    summary: "Monsoon days in the Dang forest: waterfalls, misty viewpoints and Gujarat’s only hill station.",
    overview: "Saputara sits at about 873 m in the Sahyadri hills of the Dang forest, about 420 km from Ahmedabad. Its name means “home of the serpents”. In the monsoon the forest is at its greenest: waterfalls everywhere, mist on the hills and big sunrise and sunset views. We trek, visit caves and falls, and spend a day in Vansda National Park.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Overnight bus", "The group leaves by bus in the evening, with dinner on the highway."],
      ["Saputara viewpoints", "Check in and freshen up. Eco Point, Waghbaru, Step Garden and nearby villages. Afternoon: Saputara museum, the ropeway and Sunset Point."],
      ["Gira falls & Vansda forest", "Sunrise Point and breakfast, then Gira waterfalls, the botanical garden and a forest trek in Vansda National Park with packed lunch."],
      ["Caves & forest", "Pandava caves, Mayawati waterfall, Sita Van and Shabri Dham, with packed lunch."],
      ["Lake & home", "Boating on Saputara lake and free time in the market, then the bus home."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "diu",
    name: "Diu Coastal Camp",
    region: "gujarat",
    state: "Diu (UT)",
    type: "Camp",
    days: 3,
    nights: 2,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/diu/07",
    gallery: ["cna/diu/05", "cna/diu/04", "cna/diu/02", "cna/diu/03", "cna/diu/01", "cna/diu/07", "cna/diu/06"],
    months: ["May", "Aug", "Sep", "Dec", "Jan"],
    start: "Rajkot",
    activities: ["Beach trek", "Sea caves", "Fort walk", "Coastal walks"],
    campus: null,
    featured: false,
    summary: "Calm beaches, a sea fort and coastal treks on the island of Diu.",
    overview: "Diu is a small island off the south coast of Saurashtra. Its long history ends with more than 400 years of Portuguese rule, until 1961. Today it is calm beaches, a huge sea fort, old churches and caves carved by the sea: easy, safe walking for groups. Camps run in the May and Satam-Atham holidays and from 25 December to 1 January.",
    bring: ["4 sets of clothes", "Light bedding (bed sheet + air pillow)", "2 pairs of socks", "1 woollen sweater", "Torch", "Personal medicines", "Light breakfast for the journey", "Shoulder bag + water bottle", "Cap + sunglasses", "Mosquito repellent", "Sunscreen"],
    plan: [
      ["Rajkot to Diu", "Morning bus with breakfast on the highway, reaching Diu by lunch. Rest, then an evening walk in Diu town."],
      ["Beach trek", "Coastal trek from the camp to Nagoa beach, lunch at the beach, then on to Gomtimata beach."],
      ["Fort, Fudam & home", "Diu Fort, the old church and museum, Gangeshwar Mahadev at Fudam, and Chakratirth and Jallandhar beaches. Leave around 6 pm, dinner on the way home."],
    ],
    planIsReal: true,
    reach: null,
  },
  {
    slug: "dwarka-somnath-diu",
    name: "Dwarka, Somnath & Diu",
    region: "gujarat",
    state: "Saurashtra",
    type: "Nature Trail",
    days: 4,
    nights: 3,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/upcomingtours/02",
    gallery: ["cna/upcomingtours/02"],
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    start: "Rajkot",
    activities: ["Coastal walks", "Heritage", "Beach"],
    campus: null,
    featured: false,
    summary: "The Saurashtra coast: two great temples and the beaches of Diu.",
    overview: "A coastal journey along the Saurashtra shore: Dwarka at the mouth of the Gomti, the island of Bet Dwarka, the Somnath temple by the sea and the calm beaches of Diu. Lots of sea air, sunsets and easy walks.",
    bring: null,
    plan: [
      ["Rajkot to Dwarka", "Travel together. Evening at Gomti ghat."],
      ["Bet Dwarka & beach", "Boat to Bet Dwarka, Shivrajpur beach."],
      ["To Somnath", "Coastal drive. Evening aarti at Somnath."],
      ["Diu & return", "Diu fort and beach, travel back to Rajkot."],
    ],
    planIsReal: false,
    reach: null,
  },
  {
    slug: "dwarka-somnath",
    name: "Dwarka & Somnath",
    region: "gujarat",
    state: "Saurashtra",
    type: "Nature Trail",
    days: 3,
    nights: 2,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/upcomingtours/04",
    gallery: ["cna/upcomingtours/04"],
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    start: "Rajkot",
    activities: ["Coastal walks", "Heritage", "Marine life"],
    campus: null,
    featured: false,
    summary: "Sea, temples and the coastline of western Saurashtra.",
    overview: "A short coastal trip to two of Gujarat’s best-known temple towns, Dwarka and Somnath, with time on the beaches of the Saurashtra coast.",
    bring: null,
    plan: [
      ["Rajkot to Dwarka", "Travel together. Evening aarti."],
      ["Bet Dwarka & coast", "Boat to Bet Dwarka, Shivrajpur beach, drive to Somnath."],
      ["Somnath & return", "Temple and beach, travel back to Rajkot."],
    ],
    planIsReal: false,
    reach: null,
  },
  {
    slug: "rann-of-kutch-dholavira",
    name: "Rann of Kutch & Dholavira",
    region: "gujarat",
    state: "Kutch",
    type: "Nature Trail",
    days: 3,
    nights: 2,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/upcomingtours/03",
    gallery: ["cna/upcomingtours/03"],
    months: ["Nov", "Dec", "Jan", "Feb"],
    start: "Rajkot",
    activities: ["Salt desert", "Fossil park", "Heritage site"],
    campus: null,
    featured: false,
    summary: "White salt flats and the 4,500-year-old Harappan city of Dholavira.",
    overview: "The white salt desert of the Great Rann and the 4,500-year-old Harappan city of Dholavira, a UNESCO World Heritage Site, in one short trip.",
    bring: null,
    plan: [
      ["Rajkot to Dholavira", "Travel into Kutch. Afternoon at the Harappan city ruins of Dholavira and the fossil park."],
      ["White Rann", "Drive to the Great Rann. Sunset and moonrise on the white salt desert."],
      ["Return", "Morning in a craft village, then travel back to Rajkot."],
    ],
    planIsReal: false,
    reach: null,
  },
  {
    slug: "white-rann-of-kutch",
    name: "White Rann of Kutch",
    region: "gujarat",
    state: "Kutch",
    type: "Nature Trail",
    days: 3,
    nights: 2,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/upcomingtours/05",
    gallery: ["cna/upcomingtours/05"],
    months: ["Nov", "Dec", "Jan", "Feb"],
    start: "Rajkot",
    activities: ["Full-moon salt desert", "Star gazing", "Craft villages"],
    campus: null,
    featured: false,
    summary: "Moonlight on endless white salt and the crafts of Banni villages.",
    overview: "Endless white salt under a huge sky. Sunset and moonrise on the Rann, the view from Kalo Dungar and the craft villages of Banni.",
    bring: null,
    plan: [
      ["Rajkot to the Rann", "Travel to Dhordo. Sunset on the salt."],
      ["Kalo Dungar & villages", "Highest point of Kutch, craft villages, moonlit Rann."],
      ["Return", "Travel back to Rajkot."],
    ],
    planIsReal: false,
    reach: null,
  },
  {
    slug: "gir-diu",
    name: "Gir Wildlife & Diu Beach",
    region: "gujarat",
    state: "Saurashtra",
    type: "Nature Trail",
    days: 5,
    nights: 4,
    altitude: null,
    difficulty: "Easy",
    price: null,
    img: "cna/upcomingtours/06",
    gallery: ["cna/upcomingtours/06"],
    months: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    start: "Rajkot",
    activities: ["Jungle safari", "Beach", "Bird watching"],
    campus: null,
    featured: false,
    summary: "Lion country in Gir, then sea air on the beaches of Diu.",
    overview: "Lion country in the Gir forest, then sea air on the beaches of Diu: forest and coast in one easy trip.",
    bring: null,
    plan: [
      ["Rajkot to Sasan Gir", "Travel together. Nature talk on the Gir forest."],
      ["Jungle safari", "Early safari (permits subject to availability), forest walk and bird watching."],
      ["To Diu", "Drive to the coast. Evening on Nagoa beach."],
      ["Diu", "Diu fort, sea caves and beaches."],
      ["Return", "Travel back to Rajkot."],
    ],
    planIsReal: false,
    reach: null,
  },
];

// Sample dates until CNA confirms real batches.
export const batches: Batch[] = [
  { tripSlug: "osam-hill", startDate: "2026-10-17", endDate: "2026-10-18", seatsLeft: 12, note: "Weekend" },
  { tripSlug: "astro-adventure-manali", startDate: "2026-10-21", endDate: "2026-10-29", seatsLeft: 6, note: "Diwali break" },
  { tripSlug: "sikkim-trek", startDate: "2026-11-05", endDate: "2026-11-13", seatsLeft: 9 },
  { tripSlug: "grand-uttaranchal-trek", startDate: "2026-11-14", endDate: "2026-11-22", seatsLeft: 8, note: "Girls-only batch" },
  { tripSlug: "bet-dwarka-marine-camp", startDate: "2026-11-20", endDate: "2026-11-22", seatsLeft: 20, note: "Low-tide window" },
  { tripSlug: "sasan-gir", startDate: "2026-12-11", endDate: "2026-12-13", seatsLeft: 14 },
  { tripSlug: "manali-snow-camp", startDate: "2026-12-24", endDate: "2026-12-30", seatsLeft: 10, note: "Winter break" },
];
