/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    trips: Trip;
    batches: Batch;
    posts: Post;
    reviews: Review;
    faqs: Faq;
    media: Media;
    enquiries: Enquiry;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    trips: TripsSelect<false> | TripsSelect<true>;
    batches: BatchesSelect<false> | BatchesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips".
 */
export interface Trip {
  id: string;
  name: string;
  /**
   * One or two lines for trip cards.
   */
  summary: string;
  region: 'gujarat' | 'across-india' | 'north-east' | 'outside-india';
  /**
   * State or district, e.g. Himachal Pradesh
   */
  location: string;
  type: 'trek' | 'camp' | 'nature-trail';
  difficulty: 'easy' | 'moderate' | 'challenging';
  days: number;
  /**
   * 0 shows as “Day trip”.
   */
  nights: number;
  /**
   * Leave empty for low-altitude trips.
   */
  altitudeM?: number | null;
  /**
   * Empty shows “On request”.
   */
  priceFrom?: number | null;
  /**
   * Departure city, e.g. Ahmedabad
   */
  startsFrom: string;
  /**
   * Months this trip runs.
   */
  months: ('jan' | 'feb' | 'mar' | 'apr' | 'may' | 'jun' | 'jul' | 'aug' | 'sep' | 'oct' | 'nov' | 'dec')[];
  activities?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shows “Where you stay” with the campus details.
   */
  campus?: ('manali' | 'dwarka' | 'hingolgadh') | null;
  /**
   * A short paragraph about the place. Empty uses the summary.
   */
  overview?: string | null;
  /**
   * Empty shows a sample plan sized to the trip length.
   */
  itinerary?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tick when the day-by-day plan is CNA's real schedule (otherwise it is labelled as a sample).
   */
  itineraryConfirmed?: boolean | null;
  /**
   * Empty says the group travels together from the start city.
   */
  howToReach?: string | null;
  included?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  notIncluded?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  packingList?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Main photo. Empty shows “Photo coming soon”.
   */
  heroImage?: (string | null) | Media;
  /**
   * 3 or more photos show a gallery on the trip page and an album on the Gallery page.
   */
  gallery?: (string | Media)[] | null;
  /**
   * Search engine and social sharing. Empty fields fall back to the page content.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  /**
   * Used in the URL. Leave empty to generate from name.
   */
  slug: string;
  /**
   * Lower numbers show first in trip lists.
   */
  order: number;
  /**
   * Show in “Popular trips” on the home page.
   */
  featured?: boolean | null;
  /**
   * Sample/placeholder content, labelled on the site until replaced.
   */
  isSample?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the photo for screen readers and Google, e.g. “Campers crossing a river near Manali”.
   */
  alt: string;
  /**
   * Photographer/licence for photos CNA doesn't own (shown on Photo credits).
   */
  credit?: string | null;
  /**
   * Tick only for CNA's own photos. Unticked photos must be replaced or credited before launch.
   */
  ownedByCna?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Fixed departure dates. Past batches drop off the site automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches".
 */
export interface Batch {
  id: string;
  trip: string | Trip;
  startDate: string;
  endDate: string;
  seatsLeft: number;
  /**
   * Short tag, e.g. “Diwali break”, “Girls-only batch”.
   */
  note?: string | null;
  label?: string | null;
  /**
   * Sample/placeholder content, labelled on the site until replaced.
   */
  isSample?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  excerpt: string;
  coverImage: string | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedTrips?: (string | Trip)[] | null;
  /**
   * Search engine and social sharing. Empty fields fall back to the page content.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  /**
   * Used in the URL. Leave empty to generate from title.
   */
  slug: string;
  publishedAt?: string | null;
  author?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * The 3 most recent reviews with consent appear on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  name: string;
  /**
   * e.g. “Parent · Rajkot”
   */
  role: string;
  quote: string;
  rating: number;
  trip: string | Trip;
  /**
   * The reviewer agreed to their name and words appearing on the site. Only ticked reviews are shown.
   */
  consentGiven?: boolean | null;
  /**
   * Sample/placeholder content, labelled on the site until replaced.
   */
  isSample?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shown on the About page. Ticked ones also appear on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: string;
  kind: 'quick' | 'trip' | 'group';
  status: 'new' | 'contacted' | 'booked' | 'closed';
  name: string;
  phone: string;
  email?: string | null;
  trip?: (string | null) | Trip;
  /**
   * Snapshot at the time of the enquiry.
   */
  tripName?: string | null;
  travellerType?: string | null;
  groupSize?: number | null;
  month?: ('jan' | 'feb' | 'mar' | 'apr' | 'may' | 'jun' | 'jul' | 'aug' | 'sep' | 'oct' | 'nov' | 'dec') | null;
  group?: {
    organisation?: string | null;
    /**
     * Where to (empty = suggest for us).
     */
    region?: string | null;
    days?: string | null;
    fromCity?: string | null;
    interests?: string[] | null;
  };
  message?: string | null;
  /**
   * Visible to the CNA team only.
   */
  internalNotes?: string | null;
  meta?: {
    sourcePath?: string | null;
    consentAt?: string | null;
    ipHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'trips';
        value: string | Trip;
      } | null)
    | ({
        relationTo: 'batches';
        value: string | Batch;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips_select".
 */
export interface TripsSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  region?: T;
  location?: T;
  type?: T;
  difficulty?: T;
  days?: T;
  nights?: T;
  altitudeM?: T;
  priceFrom?: T;
  startsFrom?: T;
  months?: T;
  activities?:
    | T
    | {
        text?: T;
        id?: T;
      };
  campus?: T;
  overview?: T;
  itinerary?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  itineraryConfirmed?: T;
  howToReach?: T;
  included?:
    | T
    | {
        text?: T;
        id?: T;
      };
  notIncluded?:
    | T
    | {
        text?: T;
        id?: T;
      };
  packingList?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  heroImage?: T;
  gallery?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  isSample?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batches_select".
 */
export interface BatchesSelect<T extends boolean = true> {
  trip?: T;
  startDate?: T;
  endDate?: T;
  seatsLeft?: T;
  note?: T;
  label?: T;
  isSample?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  relatedTrips?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  quote?: T;
  rating?: T;
  trip?: T;
  consentGiven?: T;
  isSample?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  ownedByCna?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  kind?: T;
  status?: T;
  name?: T;
  phone?: T;
  email?: T;
  trip?: T;
  tripName?: T;
  travellerType?: T;
  groupSize?: T;
  month?: T;
  group?:
    | T
    | {
        organisation?: T;
        region?: T;
        days?: T;
        fromCity?: T;
        interests?: T;
      };
  message?: T;
  internalNotes?: T;
  meta?:
    | T
    | {
        sourcePath?: T;
        consentAt?: T;
        ipHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero: {
    /**
     * Each entry is one line; the last line is highlighted in yellow.
     */
    headingLines: string[];
    intro: string;
    /**
     * Wide landscape photo behind the heading.
     */
    image: string | Media;
    /**
     * Small starred facts under the button.
     */
    highlights?: string[] | null;
  };
  story: {
    eyebrow: string;
    title: string;
    body: string;
    image: string | Media;
    points?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  holidays: {
    eyebrow: string;
    title: string;
    intro?: string | null;
    items?:
      | {
          /**
           * Label, e.g. Oct – Nov
           */
          months: string;
          title: string;
          /**
           * Trip names to mention.
           */
          highlights?: string[] | null;
          tripCount: number;
          /**
           * e.g. /trips?month=nov
           */
          link: string;
          image: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  destinations: {
    eyebrow: string;
    title: string;
    intro?: string | null;
    /**
     * Also used on the Destinations page.
     */
    regionImages: {
      gujarat: string | Media;
      acrossIndia: string | Media;
      northEast: string | Media;
      outsideIndia: string | Media;
    };
  };
  audiences: {
    eyebrow: string;
    title: string;
    items?:
      | {
          title: string;
          description: string;
          /**
           * e.g. /group-trips#schools
           */
          link: string;
          image: string | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Shown after “Teachers:” below the cards.
     */
    teacherNote?: string | null;
  };
  why: {
    eyebrow: string;
    title: string;
    image: string | Media;
    /**
     * Small label on the photo, e.g. Rock climbing
     */
    imageLabel?: string | null;
    points?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  gallery: {
    eyebrow: string;
    title: string;
    intro?: string | null;
    /**
     * Scrolling strip on the home page; also “CNA moments” on the Gallery page.
     */
    photos?:
      | {
          image: string | Media;
          caption: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Search engine and social sharing. Empty fields fall back to the page content.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact details and numbers used across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * As shown, e.g. +91 70463 61009
   */
  phone: string;
  /**
   * Digits with country code, e.g. 917046361009
   */
  whatsappNumber: string;
  /**
   * Pre-filled message when someone taps WhatsApp.
   */
  whatsappMessage: string;
  /**
   * Main email for enquiries.
   */
  email: string;
  /**
   * Trust office email (Contact page).
   */
  trustEmail?: string | null;
  address: {
    street: string;
    city: string;
    state: string;
    postalCode: string;
  };
  /**
   * Google Maps link to the office.
   */
  mapUrl?: string | null;
  social?:
    | {
        platform: 'Instagram' | 'Facebook' | 'YouTube' | 'X' | 'LinkedIn';
        /**
         * Leave empty to show the name without a link.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. 1,00,000+
   */
  campersCount: string;
  /**
   * e.g. 1,000+
   */
  campsCount: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headingLines?: T;
        intro?: T;
        image?: T;
        highlights?: T;
      };
  story?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        image?: T;
        points?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  holidays?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        items?:
          | T
          | {
              months?: T;
              title?: T;
              highlights?: T;
              tripCount?: T;
              link?: T;
              image?: T;
              id?: T;
            };
      };
  destinations?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        regionImages?:
          | T
          | {
              gujarat?: T;
              acrossIndia?: T;
              northEast?: T;
              outsideIndia?: T;
            };
      };
  audiences?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              link?: T;
              image?: T;
              id?: T;
            };
        teacherNote?: T;
      };
  why?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        image?: T;
        imageLabel?: T;
        points?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        photos?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  whatsappNumber?: T;
  whatsappMessage?: T;
  email?: T;
  trustEmail?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  mapUrl?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  campersCount?: T;
  campsCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}